const STYLE = `
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#07080b;color:#f5f7fa}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 20% 0%,#1b2030 0,#0b0d12 38%,#07080b 75%)}button,input{font:inherit}.shell{max-width:1100px;margin:0 auto;padding:48px 22px}.brand{display:flex;align-items:center;gap:14px}.mark{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,#fff,#8d96a8);color:#08090c;font-weight:900;box-shadow:0 12px 40px #0008}.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:11px;color:#8e98aa}.title{font-size:42px;line-height:1;margin:12px 0 10px;letter-spacing:-.04em}.sub{color:#aab2c0;max-width:680px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:30px 0}.card{background:#101319cc;border:1px solid #252b36;border-radius:20px;padding:20px;box-shadow:0 16px 50px #0005;backdrop-filter:blur(18px)}.label{font-size:12px;color:#8d97a8}.value{font-size:20px;font-weight:700;margin-top:7px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#7df2b3;margin-right:8px;box-shadow:0 0 12px #7df2b3}.search{display:flex;gap:10px;margin:20px 0}.search input{flex:1;background:#0d1016;border:1px solid #2a303b;color:#fff;border-radius:14px;padding:14px 16px;outline:none}.search button{border:0;border-radius:14px;padding:0 18px;background:#f3f5f7;color:#08090c;font-weight:750;cursor:pointer}.tools{display:grid;gap:10px}.tool{padding:16px;border:1px solid #252b36;background:#0c0f14;border-radius:16px}.tool strong{display:block;margin-bottom:5px}.tool span{font-size:13px;color:#9ba4b3;line-height:1.45}.footer{margin-top:30px;color:#697384;font-size:12px}.pill{display:inline-flex;padding:6px 9px;border:1px solid #303744;border-radius:999px;color:#aeb7c6;font-size:11px;margin:4px 4px 0 0}.btn{border:0;border-radius:12px;padding:12px 16px;background:#f3f5f7;color:#08090c;font-weight:750;cursor:pointer;text-decoration:none;display:inline-block;font-size:14px}.btn.ghost{background:transparent;border:1px solid #39414f;color:#cfd6e0}.btn:disabled{opacity:.5;cursor:default}.row{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px;align-items:center}code{display:inline-block;background:#0a0d12;border:1px solid #262d38;border-radius:8px;padding:6px 8px;font-size:12px;color:#cfd6e0;user-select:all;-webkit-user-select:all;word-break:break-all}@media(max-width:760px){.grid{grid-template-columns:1fr 1fr}.title{font-size:34px}.shell{padding-top:30px}}@media(max-width:480px){.grid{grid-template-columns:1fr}}
`;

function page(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DEMO MCP</title><style>${STYLE}</style></head><body><main class="shell"><div class="brand"><div class="mark">D</div><div><div class="eyebrow">Independent MCP execution layer</div><strong>DEMO</strong></div></div><h1 class="title">Browse. Explore. Execute.</h1><p class="sub">DEMO runs its own browser, skills and MCP tools on the Worker. The Platform is the control center; DEMO MCP is the execution layer.</p><section class="grid"><div class="card"><div class="label">Worker</div><div class="value"><i class="dot"></i><span id="status">Checking…</span></div></div><div class="card"><div class="label">Version</div><div class="value" id="version">—</div></div><div class="card"><div class="label">Tools</div><div class="value" id="tools">—</div></div><div class="card"><div class="label">Browser</div><div class="value" id="browser">Checking…</div></div></section><section class="card"><div class="eyebrow">Capabilities</div><div id="capabilities" class="tools"><div class="tool"><strong>Loading DEMO state…</strong><span>Safe telemetry contains no credentials or user content.</span></div></div></section><section class="card" style="margin-top:14px" id="robloxCard"><div class="eyebrow">Roblox account</div><div class="tool"><strong id="robloxTitle">Checking link…</strong><span id="robloxDetail">The account tools read your profile and inventory through Roblox's official OAuth 2.0 flow. Tokens stay on the Worker.</span><div id="robloxScopes"></div><div class="row"><button class="btn" id="robloxConnect" type="button" hidden>Connect Roblox account</button><button class="btn ghost" id="robloxDisconnect" type="button" hidden>Disconnect</button><button class="btn ghost" id="robloxRefresh" type="button">Check again</button></div><div class="label" id="robloxRedirect" hidden style="margin-top:12px">Redirect URL to register at create.roblox.com:<br><code id="robloxRedirectValue"></code></div><div class="label" id="robloxStorage" style="margin-top:10px"></div></div></section><section class="card" style="margin-top:14px"><div class="eyebrow">MCP endpoint</div><div class="tool"><strong>/mcp</strong><span>Connect an MCP client to DEMO's execution layer. Browser screenshots are stored externally and returned as compact links.</span></div></section><div class="footer">DEMO MCP is independent. No third-party gateway is required for its core skills and browser capabilities.</div></main><script>
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
async function boot(){try{const x=await getJson('/platform/stats');document.getElementById('status').textContent=x.status==='online'?'Online':'Degraded';document.getElementById('version').textContent=x.version||'—';document.getElementById('tools').textContent=x.toolCount??'—';document.getElementById('browser').textContent=x.capabilities?.browserWatching?'Ready':'Unavailable';const c=x.capabilities||{};document.getElementById('capabilities').innerHTML=Object.entries(c).filter(([k])=>k!=='composio').map(([k,v])=>'<div class="tool"><strong>'+esc(k)+'</strong><span>'+esc(String(v))+'</span></div>').join('')}catch(e){document.getElementById('status').textContent='Offline';document.getElementById('capabilities').innerHTML='<div class="tool"><strong>Telemetry unavailable</strong><span>'+esc(String(e))+'</span></div>'}}

async function robloxStatus(){const r=await fetch('/oauth/roblox/status',{cache:'no-store',headers:{Accept:'application/json'}});const x=await r.json();if(!r.ok){const e=x||{};return{configured:false,code:e.error||'unknown',message:e.message||'Roblox status unavailable.',hint:e.hint||''}}return Object.assign({configured:true},x)}
function pill(v){return '<span class="pill">'+esc(v)+'</span>'}
async function roblox(){const t=document.getElementById('robloxTitle'),d=document.getElementById('robloxDetail'),sc=document.getElementById('robloxScopes'),st=document.getElementById('robloxStorage'),rd=document.getElementById('robloxRedirect'),rv=document.getElementById('robloxRedirectValue'),cb=document.getElementById('robloxConnect'),ub=document.getElementById('robloxDisconnect');try{const x=await robloxStatus();if(!x.configured){t.textContent='Not configured';sc.innerHTML=pill(x.code);d.textContent=x.message;st.textContent=x.hint||'';return}const c=x.configuration||{};const a=x.account;rd.hidden=!c.redirectUri;if(c.redirectUri)rv.textContent=c.redirectUri;st.textContent='Token storage: '+(c.storage==='durable-object'?'Durable Object (encrypted at rest)':'Worker memory (temporary)')+' · client '+(c.clientIdConfigured?'ok':'missing')+' · secret '+(c.clientSecretConfigured?'ok':'missing');if(x.connected&&a){t.textContent='Connected as '+(a.username?'@'+a.username:(a.displayName||a.userId||'your Roblox account'))+((a.displayName&&a.username&&a.displayName!==a.username)?' ('+a.displayName+')':'');d.textContent='Roblox user id (sub) '+(a.userId||'—')+' · access token valid until '+String(a.accessTokenExpiresAt||'—')+(a.canRefresh?' · refresh available':' · cannot refresh');sc.innerHTML=(a.grantedScopes||[]).map(pill).join('');cb.hidden=true;ub.hidden=false}else if(a&&a.reauthorizationRequired){t.textContent='Link needs to be refreshed';d.textContent=a.reauthorizationReason||'Roblox refused the stored credentials.';sc.innerHTML='';cb.hidden=false;ub.hidden=false}else{t.textContent=c.enabled?'Not connected':'Disabled';d.textContent=c.enabled?'Tap Connect Roblox account, sign in at roblox.com in this same tab, then approve the scopes.':'Set ROBLOX_CLIENT_ID and the ROBLOX_CLIENT_SECRET secret on this Worker.';sc.innerHTML=(c.requestedScopes||[]).map(pill).join('');cb.hidden=!c.enabled;ub.hidden=true}}catch(e){t.textContent='Status unavailable';d.textContent=String(e)+' — the link below still works.';cb.hidden=false}}
async function robloxUnlink(){const b=document.getElementById('robloxDisconnect');b.disabled=true;b.textContent='Disconnecting…';try{await fetch('/oauth/roblox/logout',{method:'POST',headers:{Accept:'application/json'}})}catch(e){}b.disabled=false;b.textContent='Disconnect';await roblox()}
document.getElementById('robloxConnect').addEventListener('click',function(){location.href='/oauth/roblox/start'});
document.getElementById('robloxDisconnect').addEventListener('click',robloxUnlink);
document.getElementById('robloxRefresh').addEventListener('click',roblox);
function esc(v){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
boot();roblox();
</script></body></html>`;
}
export function demoUi(): Response { return new Response(page(), { headers: { "content-type": "text/html; charset=UTF-8", "cache-control": "no-store" } }); }
