const STYLE = `
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#07080b;color:#f5f7fa}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 20% 0%,#1b2030 0,#0b0d12 38%,#07080b 75%)}button,input{font:inherit}.shell{max-width:1100px;margin:0 auto;padding:48px 22px}.brand{display:flex;align-items:center;gap:14px}.mark{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,#fff,#8d96a8);color:#08090c;font-weight:900;box-shadow:0 12px 40px #0008}.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:11px;color:#8e98aa}.title{font-size:42px;line-height:1;margin:12px 0 10px;letter-spacing:-.04em}.sub{color:#aab2c0;max-width:680px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:30px 0}.card{background:#101319cc;border:1px solid #252b36;border-radius:20px;padding:20px;box-shadow:0 16px 50px #0005;backdrop-filter:blur(18px)}.label{font-size:12px;color:#8d97a8}.value{font-size:20px;font-weight:700;margin-top:7px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#7df2b3;margin-right:8px;box-shadow:0 0 12px #7df2b3}.search{display:flex;gap:10px;margin:20px 0}.search input{flex:1;background:#0d1016;border:1px solid #2a303b;color:#fff;border-radius:14px;padding:14px 16px;outline:none}.search button{border:0;border-radius:14px;padding:0 18px;background:#f3f5f7;color:#08090c;font-weight:750;cursor:pointer}.tools{display:grid;gap:10px}.tool{padding:16px;border:1px solid #252b36;background:#0c0f14;border-radius:16px}.tool strong{display:block;margin-bottom:5px}.tool span{font-size:13px;color:#9ba4b3;line-height:1.45}.footer{margin-top:30px;color:#697384;font-size:12px}.pill{display:inline-flex;padding:6px 9px;border:1px solid #303744;border-radius:999px;color:#aeb7c6;font-size:11px;margin:4px 4px 0 0}@media(max-width:760px){.grid{grid-template-columns:1fr 1fr}.title{font-size:34px}.shell{padding-top:30px}}@media(max-width:480px){.grid{grid-template-columns:1fr}}
`;

function page(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DEMO MCP</title><style>${STYLE}</style></head><body><main class="shell"><div class="brand"><div class="mark">D</div><div><div class="eyebrow">Independent MCP execution layer</div><strong>DEMO</strong></div></div><h1 class="title">Browse. Explore. Execute.</h1><p class="sub">DEMO runs its own browser, skills and MCP tools on the Worker. The Platform is the control center; DEMO MCP is the execution layer.</p><section class="grid"><div class="card"><div class="label">Worker</div><div class="value"><i class="dot"></i><span id="status">Checking…</span></div></div><div class="card"><div class="label">Version</div><div class="value" id="version">—</div></div><div class="card"><div class="label">Tools</div><div class="value" id="tools">—</div></div><div class="card"><div class="label">Browser</div><div class="value" id="browser">Checking…</div></div></section><section class="card"><div class="eyebrow">Capabilities</div><div id="capabilities" class="tools"><div class="tool"><strong>Loading DEMO state…</strong><span>Safe telemetry contains no credentials or user content.</span></div></div></section><section class="card" style="margin-top:14px"><div class="eyebrow">MCP endpoint</div><div class="tool"><strong>/mcp</strong><span>Connect an MCP client to DEMO's execution layer. Browser screenshots are stored externally and returned as compact links.</span></div></section><div class="footer">DEMO MCP is independent. No third-party gateway is required for its core skills and browser capabilities.</div></main><script>
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
async function boot(){try{const x=await getJson('/platform/stats');document.getElementById('status').textContent=x.status==='online'?'Online':'Degraded';document.getElementById('version').textContent=x.version||'—';document.getElementById('tools').textContent=x.toolCount??'—';document.getElementById('browser').textContent=x.capabilities?.browserWatching?'Ready':'Unavailable';const c=x.capabilities||{};document.getElementById('capabilities').innerHTML=Object.entries(c).filter(([k])=>k!=='composio').map(([k,v])=>'<div class="tool"><strong>'+esc(k)+'</strong><span>'+esc(String(v))+'</span></div>').join('')}catch(e){document.getElementById('status').textContent='Offline';document.getElementById('capabilities').innerHTML='<div class="tool"><strong>Telemetry unavailable</strong><span>'+esc(String(e))+'</span></div>'}}
function esc(v){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}boot();
</script></body></html>`;
}
export function demoUi(): Response { return new Response(page(), { headers: { "content-type": "text/html; charset=UTF-8", "cache-control": "no-store" } }); }
