/**
 * GENERATED FILE — do not edit by hand.
 *
 * Tool catalog for the DEMO inspector UI, extracted from the real MCP tool
 * registrations (index.ts + src/mcp/*.ts) by scripts/generate-tool-catalog.mjs.
 * tests/tool-catalog.test.ts pins this list against DEMO_TOOL_NAMES so it can
 * never drift from the live tool surface. Contains no secrets and no values —
 * only static registration metadata.
 */

export interface DemoToolCatalogEntry {
  name: string;
  title: string;
  group: string;
  /** Which live capability gates this tool: browser | youtube | jev | laya |
   * transcription | vision | frames | artifacts | snapshots | oauth | always.
   * "oauth" = protected tool requiring a user-bound DEMO OAuth grant. */
  availability: string;
  description?: string;
  inputs?: string[];
}

export const TOOL_CATALOG_VERSION = "0.9.0";

export const TOOL_CATALOG: DemoToolCatalogEntry[] = [
  { name: "archive_item", title: "Internet Archive Item", group: "Internet Archive", availability: "always", description: "Retrieve metadata and the available file listing for an archive.org item by identifier (structured item layout). Reports restricted/unavailable items explicitly (access_restricted) instead of pretending they can be fetched. No API key required.", inputs: ["identifier", "max_files"] },
  { name: "archive_search", title: "Search the Internet Archive", group: "Internet Archive", availability: "always", description: "Search the Internet Archive. scope=items searches public archive.org items (texts, audio, movies, software, web collections…); scope=web searches *archived webpages* for a URL/host through the Wayback CDX index and lists captures. No API key required. Returns original URLs and archive timestamps — and when nothing is archived it says so plainly instead of inventing results.", inputs: ["scope", "query", "limit", "page", "mediatype", "from", "to", "match_type"] },
  { name: "browser_capabilities", title: "Browser Capabilities", group: "Browser", availability: "browser", description: "Report which browser capabilities are available in this deployment and which Cloudflare binding or plan they need." },
  { name: "browser_captcha_cancel", title: "Browser CAPTCHA Cancel", group: "Browser", availability: "browser", description: "Explicitly abandon an open CAPTCHA handoff (user fallback). Keeps the browser session, tab and page state; marks the handoff CANCELLED and returns automation control without touching the challenge.", inputs: ["session_id", "page_id", "reason"] },
  { name: "browser_captcha_handoff", title: "Browser CAPTCHA Handoff", group: "Browser", availability: "browser", description: "CAPTCHA/bot-verification workflow: detect the challenge, immediately pause automation, keep the SAME browser session alive, open a Live View for the user and store a resumable task snapshot. Demo never solves or bypasses the challenge — the human completes it in the live browser and Demo resumes the task automatically.", inputs: ["session_id", "page_id", "timeout_ms", "instructions", "mode", "task_workflow", "task_step", "task_context"] },
  { name: "browser_captcha_wait", title: "Browser CAPTCHA Wait", group: "Browser", availability: "browser", description: "Monitor an open CAPTCHA handoff for up to 30s: polls the live page (no reloads, no session rotation) and returns as soon as the challenge is completed (automatic resume), failed, timed out, cancelled or the session died. Repeat calls to keep monitoring until a terminal outcome.", inputs: ["session_id", "page_id", "wait_ms", "interval_ms"] },
  { name: "browser_challenge_status", title: "Browser Challenge Status", group: "Browser", availability: "browser", description: "Classify the current page as normal, loading, login required, consent required, CAPTCHA, bot check, access denied or unavailable. DEMO never solves or bypasses challenges.", inputs: ["session_id", "page_id", "url", "screenshot"] },
  { name: "browser_click", title: "Browser Click", group: "Browser", availability: "browser", description: "Click a visible element addressed by CSS selector, text:…, role:button:Name, or ref:eN from browser_snapshot.", inputs: ["target", "session_id", "page_id", "url", "timeout", "screenshot"] },
  { name: "browser_close", title: "Browser Close", group: "Browser", availability: "browser", description: "Close a browser session and release the Cloudflare Browser Run instance immediately.", inputs: ["session_id"] },
  { name: "browser_console", title: "Browser Console", group: "Browser", availability: "browser", description: "Capture console messages and page errors during navigation.", inputs: ["url"] },
  { name: "browser_evaluate", title: "Browser Evaluate", group: "Browser", availability: "browser", description: "Run JavaScript inside the webpage context.", inputs: ["url", "expression"] },
  { name: "browser_fill", title: "Browser Fill", group: "Browser", availability: "browser", description: "Open a page and fill an input or textarea.", inputs: ["url", "target", "value"] },
  { name: "browser_inspect", title: "Browser Inspect", group: "Browser", availability: "browser", description: "Open a website and inspect its visible structure and interactive elements.", inputs: ["url"] },
  { name: "browser_media_info", title: "Browser Media Info", group: "Browser", availability: "browser", description: "Inspect publicly exposed media on the page: video/audio elements, poster, duration, dimensions, source URLs, OpenGraph/Twitter metadata, JSON-LD and (for public TikTok pages) the video's author, caption, id, thumbnail, duration and exposed media URLs. Reports honestly when media is hidden, protected or behind a challenge.", inputs: ["session_id", "page_id", "url", "selector"] },
  { name: "browser_open", title: "Browser Open", group: "Browser", availability: "browser", description: "Open a URL in DEMO's Cloudflare browser session, follow redirects, and return the final URL, title, page stats and challenge status. Pass the returned session_id to later browser tools to keep working on the same rendered page.", inputs: ["url", "session_id", "page_id", "wait_until", "timeout", "settle_ms", "screenshot"] },
  { name: "browser_pause_for_human", title: "Browser Pause For Human", group: "Browser", availability: "browser", description: "Pause automation and hand the live page to a human (CAPTCHA, login, consent, bot check). Returns a Live View URL; the browser session is kept alive while the human works. DEMO does not solve, bypass or pre-empt any challenge.", inputs: ["session_id", "page_id", "instructions", "timeout_ms", "mode"] },
  { name: "browser_press", title: "Browser Press", group: "Browser", availability: "browser", description: "Open a page and press a key.", inputs: ["url", "key", "target"] },
  { name: "browser_read", title: "Browser Read", group: "Browser", availability: "browser", description: "Read the rendered page: visible text, metadata, links, headings, interactive elements and media counts. This reads the DOM after JavaScript execution, not the raw HTTP response.", inputs: ["session_id", "page_id", "url", "selector", "max_text_chars", "max_links", "include_html", "format"] },
  { name: "browser_resume", title: "Browser Resume", group: "Browser", availability: "browser", description: "Re-check the page after a human completed (or abandoned) a challenge and continue automation. Reports whether the blocking state is gone; it never claims to have bypassed anything.", inputs: ["session_id", "page_id", "reload", "wait_ms", "screenshot"] },
  { name: "browser_run", title: "Browser Run", group: "Browser", availability: "browser", description: "Run a multi-step browser workflow in one independent Chromium page. Screenshots are returned as external links, not image payloads.", inputs: ["url", "actions", "screenshotEvery"] },
  { name: "browser_screenshot", title: "Browser Screenshot", group: "Browser", availability: "browser", description: "Capture the viewport, the full page, or a single element of the current page. The image is stored in Cloudflare R2 and returned as a compact link (not inline bytes) unless inline=true.", inputs: ["session_id", "page_id", "url", "type", "full_page", "selector", "inline", "quality"] },
  { name: "browser_scroll", title: "Browser Scroll", group: "Browser", availability: "browser", description: "Scroll the page down, up, left, right, or jump to the top/bottom.", inputs: ["direction", "amount", "session_id", "page_id", "url"] },
  { name: "browser_session", title: "Browser Session", group: "Browser", availability: "browser", description: "Inspect, create or close a persistent browser session (tabs, keep-alive, provider state).", inputs: ["action", "session_id"] },
  { name: "browser_snapshot", title: "Browser Snapshot", group: "Browser", availability: "browser", description: "Return an accessibility tree and/or a simplified interactive DOM with ref ids (ref:e3) that browser_click and browser_type can address.", inputs: ["session_id", "page_id", "url", "mode", "max_nodes", "max_elements"] },
  { name: "browser_tabs", title: "Browser Tabs", group: "Browser", availability: "browser", description: "List, open, close or switch between tabs in a browser session.", inputs: ["session_id", "action", "page_id", "url"] },
  { name: "browser_task", title: "Browser Task", group: "Browser", availability: "browser", description: "Prepare a natural multi-step browser task and optionally request visual checkpoints.", inputs: ["url", "task", "skillIds", "screenshotEvery"] },
  { name: "browser_type", title: "Browser Type", group: "Browser", availability: "browser", description: "Type text into a field. The typed value is never logged, never echoed back and never included in results — only its length is reported. Mark secret=true for credentials.", inputs: ["target", "text", "session_id", "page_id", "url", "clear", "submit", "secret", "delay_ms"] },
  { name: "browser_video_frames", title: "Browser Video Frames", group: "Browser", availability: "browser", description: "Sample a bounded number of rendered frames from a publicly playable <video> element by seeking and screenshotting the pixels on screen. Nothing is downloaded and DRM-protected media is never touched.", inputs: ["session_id", "page_id", "url", "count", "index", "selector", "timestamps", "type"] },
  { name: "browser_wait", title: "Browser Wait", group: "Browser", availability: "browser", description: "Wait for a selector, text, URL change, network idle, or a fixed delay.", inputs: ["session_id", "page_id", "url", "selector", "text", "wait_url", "network_idle", "milliseconds", "timeout", "idle_ms"] },
  { name: "browser_watch", title: "Browser Watch", group: "Browser", availability: "browser", description: "Actively explore a website with DEMO's independent browser, taking external screenshot checkpoints while returning compact page state.", inputs: ["url", "actions", "screenshotEvery", "includeInteractiveState"] },
  { name: "cron_explain", title: "Cron Expression Helper", group: "Utilities", availability: "always", description: "Validate and explain a cron expression in human-readable language and compute upcoming execution times. Supports standard 5-field cron, the common 6-field seconds extension and @yearly/@monthly/@weekly/@daily/@hourly macros, with lists, ranges, steps and month/weekday names (Vixie day-of-month/day-of-week OR semantics). Malformed expressions return a precise error. Entirely local — no external service.", inputs: ["expression", "count", "from", "horizon_days"] },
  { name: "demo_ping", title: "DEMO Ping", group: "Core", availability: "always", description: "Check DEMO status, version and capabilities." },
  { name: "feed_read", title: "Read RSS / Atom Feed", group: "Feeds", availability: "always", description: "Fetch and parse an RSS 2.x, Atom or RDF feed (or parse inline XML) into feed metadata + entries: titles, links, GUIDs/ids, publication and update dates, authors, categories/tags, descriptions/content and enclosures. Accepts a feed URL — or a page URL whose <link rel=alternate> advertises feeds (they are returned as suggestions). Malformed feeds degrade gracefully with warnings; entry limits are configurable. No API key; content is fetched read-only through DEMO's SSRF-guarded HTTP client and never stored.", inputs: ["url", "xml", "limit", "timeout_ms"] },
  { name: "generate_uuid", title: "Generate UUID", group: "Core", availability: "always", description: "Generate a random UUID." },
  { name: "git_repository", title: "Public Git Repository", group: "Git", availability: "always", description: "Inspect a PUBLIC Git repository over the standard Git smart-HTTP protocol — works with GitHub, GitLab, Codeberg, Gitea, sourcehut or any compatible host, with NO API key and NO credentials. Modes: info (metadata + default branch), branches, tags, log (history with changed files per commit via include_changes), commit (one commit + changed files), file (read a file at any revision), tree (structure), search (content search at a revision), compare (two revisions: structured diffs + patch), patch (export a commit as a patch), stats (basic statistics), ignore (.gitignore inspection + path tests), fetch (re-fetch state). Private repositories return auth_required — DEMO never accepts, requests or stores Git credentials. Repository contents are treated as untrusted data: hooks, LFS, build scripts and repository automation are never executed. Temporary clones are size/time limited and cleaned up automatically.", inputs: ["mode", "url", "rev", "path", "query", "base", "head", "limit", "depth", "include_changes", "case_insensitive", "regex", "test_paths", "refresh", "timeout_ms"] },
  { name: "hash_text", title: "Hash Text", group: "Core", availability: "always", description: "Create a SHA-256 or SHA-512 hash.", inputs: ["text", "algorithm"] },
  { name: "http_fetch", title: "HTTP Fetch", group: "Core", availability: "always", description: "Fetch an HTTP(S) URL and return bounded text. Private/internal targets — including redirect hops into them — are blocked unless SSRF_GUARD_HTTP_FETCH=false.", inputs: ["url", "method"] },
  { name: "image_analyze", title: "Image Analysis", group: "Documents", availability: "always", description: "Fetch a PUBLIC image and analyze it with DEMO's existing Workers AI vision binding (the same pipeline the video tools use — no second vision API). mode=info (format, dimensions, size, hash), mode=describe (factual description), mode=ocr (transcribe visible text), mode=analyze (structured visible-text/objects/scene JSON), mode=compare (2-4 images: per-image metadata+descriptions plus coarse similarity). When no AI binding is configured, info still works and AI-derived fields report unavailable — DEMO never invents descriptions or text. Size limits and SSRF protection apply.", inputs: ["mode", "urls", "timeout_ms"] },
  { name: "inspect_video", title: "Inspect Video (Watch, Understand & React)", group: "Video", availability: "vision", description: "Automatic video viewing and understanding from a URL alone — the ONLY tool needed when a user sends a video link. Resolves the platform and actual media (direct MP4/WebM files, public video pages, TikTok/Instagram/X/Reddit links including vt./vm. short URLs), extracts REAL decoded frames from throughout the video in Cloudflare Browser Rendering (first, middle, final and intent-biased moments — never thumbnails or cover images), and returns them as MCP image content blocks a vision model can examine directly, plus structured context: source metadata, detected scenes, on-screen text, honest audio status. CALL AUTOMATICALLY when a user sends a public video URL and asks 'What do you think of this?', 'React to this.', 'Watch this.', 'What happens?', 'Is this real?', 'Is this funny?', 'Explain this video.', 'Rate the vibe.', 'Look at this', 'What does the text say?', or pastes only a link with no explanation — pass the user's original message as userIntent and their explicit question as question; reaction mode and the frame plan are then derived automatically. Never ask the user to download the video, extract frames, upload screenshots, or provide timestamps. RESPONSE CONTRACT: the returned image blocks are the visual evidence. When visualEvidenceDelivered=true, examine the frames and answer the user's intent naturally — for reaction requests give a genuine, context-aware reaction matching the user's tone instead of a robotic metadata summary; mention uncertainty where the frames do not establish something. When visualEvidenceDelivered=false the inspection failed: say so honestly and NEVER claim to have seen or watched the video. Frames are samples, not continuous playback: do not claim to have watched the whole video, and never invent audio, dialogue, or events outside the frames.", inputs: ["url", "userIntent", "question", "reactionMode", "frameCount", "timestamps", "includeMetadata", "includeAudio", "analyzeScenes", "analyzeOnScreenText"] },
  { name: "jev_capabilities", title: "Jev Decision Engine Capabilities", group: "JEV", availability: "jev", description: "Report whether this deployment can ask TypeSafe/Jev for typed decisions, which model and thresholds it uses, every decision template with its allowed answers and fallback, and what the engine must never do. Configuration presence only — no credential value. Also available as the demo://capabilities/jev resource and as flags in demo_ping, /health and /platform/stats." },
  { name: "jev_decide", title: "Ask Jev for a Typed Decision", group: "JEV", availability: "oauth", description: "Run one of DEMO's predefined typed-decision templates (TypeSafe/Jev and/or Laya, per the provider argument and DECISION_PROVIDER_MODE) over the text you supply and return the typed answer with its probabilities, confidence and how DEMO's policy treated it. Choices are limited to the options in code: this is a judgment primitive, not a chat model, and it cannot call tools or authorize anything. This tool can incur paid provider usage and requires the user-bound DEMO OAuth scope decision:use. Returns the deterministic fallback with policy `unavailable_fallback` when no provider is configured or every provider fails.", inputs: ["decision", "request", "result", "evidence", "provider"] },
  { name: "json_format", title: "Format JSON", group: "Core", availability: "always", description: "Validate and pretty-print JSON.", inputs: ["json"] },
  { name: "jwt_inspect", title: "Inspect a JWT (decode only)", group: "Utilities", availability: "always", description: "DECODE a JWT/JWS (compact three-part form): structure check, header decoding (alg, typ, kid…), payload/claims decoding with exp/iat/nbf/iss/aud/sub inspection and expiry-window status. DECODING ≠ VERIFICATION — the result always says verification: not-performed and a decodable token is NEVER claimed to be valid or authentic. No signing key is requested, accepted or stored (there is no verification path at all). The complete token is never returned or logged — only decoded parts (redacted) and a short SHA-256 fingerprint.", inputs: ["token", "now"] },
  { name: "laya_capabilities", title: "Laya Decision Provider Capabilities", group: "Laya", availability: "laya", description: "Report whether this deployment routes typed decisions to an external Laya server (enabled/configured/reachable configuration, routing mode auto|laya|jev with the fallback chain, budgets, and the safety boundary). DEMO never hosts the Laya model; the endpoint is reported as a hostname and no credential value is ever included. Also available as the demo://capabilities/laya resource and as flags in demo_ping, /health and /platform/stats." },
  { name: "net_diagnose", title: "Network Diagnostics", group: "Network", availability: "always", description: "Safe PUBLIC-network diagnostics for one hostname/URL at a time (never a scanner): mode=dns (DNS records via DNS-over-HTTPS: A/AAAA/MX/NS/TXT/CNAME/SOA/CAA/SRV with TTLs), mode=http (status, redirect chain with per-hop safety verdicts, response headers, timing, resolved addresses), mode=tls (certificate issuer/subject/expiry via the existing browser binding when available — reported unavailable otherwise, never guessed), mode=full (all of the above). localhost, private ranges, link-local, metadata endpoints and internal names are refused, not probed. No port scanning, no sweeps, no service fingerprinting.", inputs: ["mode", "target", "record_types", "max_redirects", "method"] },
  { name: "openapi_inspect", title: "OpenAPI Inspector", group: "Network", availability: "always", description: "Inspect a public OpenAPI 3.x document (or Swagger 2.0 where practical) in JSON or YAML: API title/version/description, servers, paths with HTTP methods, parameters, request bodies, response schemas, authentication/security schemes (names and types only — never credentials), reusable component schemas and endpoint summaries. Provide a public URL or inline document. DEMO READS the document and never calls the APIs it describes; remote $ref targets are never fetched. SSRF, size and timeout limits apply to the fetch.", inputs: ["url", "document", "max_endpoints", "timeout_ms"] },
  { name: "pdf_document", title: "PDF Document Intelligence", group: "Documents", availability: "always", description: "Download and inspect a PUBLIC PDF: mode=info (metadata + page count + scanned detection), mode=text (page-by-page text with page numbers preserved), mode=pages (per-page structure: characters, lines, embedded images, tables), mode=search (find text with page/line references), mode=tables (extracted table candidates), mode=ocr (OCR scanned/image-only pages through DEMO's existing Workers AI vision binding — reports unavailable instead of inventing text when no AI binding exists). Scanned PDFs are detected explicitly. PDFs are untrusted input: nothing inside them is executed. Size/timeout limits and SSRF protection apply like every other fetch.", inputs: ["mode", "url", "pages", "max_pages", "query", "case_insensitive", "regex", "timeout_ms"] },
  { name: "roblox_account_avatar_thumbnail", title: "Roblox Authenticated Avatar Thumbnail", group: "Roblox", availability: "oauth", description: "Generate the linked user's avatar thumbnail through the official Open Cloud long-running operation and return its public image URL. The DEMO OAuth identity selects the account. Requires roblox:read.", inputs: ["size", "format", "shape"] },
  { name: "roblox_account_capabilities", title: "Roblox Account Capability Matrix", group: "Roblox", availability: "oauth", description: "Report the Roblox actions DEMO may perform for the account bound to this authenticated DEMO identity, together with the scopes and unsupported actions. No account selector is accepted. Requires roblox:read." },
  { name: "roblox_account_inventory", title: "Roblox Authenticated Inventory", group: "Roblox", availability: "oauth", description: "List the linked user's own Roblox inventory items through the official Open Cloud endpoint. This requires the Roblox user.inventory-item:read scope plus that user's privacy setting. No user id or account selector is accepted. Requires roblox:read in DEMO and the separate Roblox scope.", inputs: ["maxPageSize", "pageToken", "filter", "assertAssetIds"] },
  { name: "roblox_account_link_start", title: "Start Roblox Account Link", group: "Roblox", availability: "oauth", description: "Create a short-lived, single-use code that binds a Roblox OAuth authorization to this authenticated DEMO identity. This does not sign in to Roblox or grant Roblox access; the user must open DEMO's link page and approve on Roblox's official consent screen. Requires roblox:link and roblox:read." },
  { name: "roblox_account_profile", title: "Roblox Authenticated Profile", group: "Roblox", availability: "oauth", description: "Fetch the linked user's own Roblox profile with the server-side token. Set extended=true to also read Open Cloud GET /cloud/v2/users/{id}, requiring user.advanced:read or user.social:read on the Roblox app. The DEMO identity—not a tool argument—selects the linked account. Requires roblox:read.", inputs: ["extended"] },
  { name: "roblox_account_status", title: "Roblox Account Status", group: "Roblox", availability: "oauth", description: "Report the Roblox grant linked to the identity represented by this DEMO OAuth token. No account id or slot can be supplied. Returns only safe account metadata and encryption/storage status; it never returns an access token, refresh token, ID token, cookie or secret. Requires roblox:read." },
  { name: "roblox_account_unlink", title: "Disconnect Roblox Account", group: "Roblox", availability: "oauth", description: "Revoke the Roblox authorization when possible and delete the encrypted grant bound to this DEMO identity. This is the only account affected; no account id can be supplied. Requires roblox:disconnect." },
  { name: "roblox_game", title: "Roblox Experience Lookup", group: "Roblox", availability: "always", description: "Look up Roblox experience information by universe ID.", inputs: ["universeId"] },
  { name: "roblox_user", title: "Roblox User Lookup", group: "Roblox", availability: "always", description: "Look up a Roblox user by username.", inputs: ["username"] },
  { name: "schema_validate", title: "Validate JSON against a Schema", group: "Utilities", availability: "always", description: "Validate a JSON document against a JSON Schema (draft-07 / 2019-09 / 2020-12 practical subset: type, enum, const, properties, required, additionalProperties, items/prefixItems, numeric/string bounds, pattern, format subset, allOf/anyOf/oneOf/not, if/then/else, internal $ref). Returns valid/invalid plus EXACT failing JSON-pointer paths, the expected schema constraint, the received value/type and useful messages. Entirely local — user data is never sent to an external service. Remote $ref targets are refused (never fetched) and unsupported keywords are reported in warnings, not silently ignored.", inputs: ["instance", "schema", "max_errors"] },
  { name: "screenshot_diff", title: "Screenshot Comparison", group: "Browser", availability: "browser", description: "Compare two screenshots visually using DEMO's existing browser + screenshot infrastructure. Inputs are screenshot references (from browser_screenshot/browser_workflow) or public image URLs. Runs a real pixel comparison in the Cloudflare browser (canvas work in-page) and returns changed-pixel ratio, changed-region bounding boxes and a stored difference image (same link format and TTL as screenshots). Without the browser binding it degrades to an honest metadata-only comparison — never a fabricated pixel diff.", inputs: ["a", "b", "threshold", "grid", "store_diff_image"] },
  { name: "skill_builtin_caveman", title: "Use Built-in Caveman Skill", group: "Skills", availability: "always", description: "Return DEMO's bundled Caveman skill instructions for the current task." },
  { name: "skill_builtin_typesafe", title: "Use Built-in TypeSafe Skill", group: "Skills", availability: "always", description: "Return DEMO's bundled TypeSafe/Jev skill guidance for the current task." },
  { name: "skill_install_info", title: "Skill Install Command", group: "Skills", availability: "always", description: "Return the standard skills CLI command without executing it.", inputs: ["installUrl"] },
  { name: "skills_audit", title: "Audit skill on skills.sh", group: "Skills", availability: "always", description: "Retrieve available security audit results for a skills.sh skill.", inputs: ["id"] },
  { name: "skills_browse", title: "Browse skills.sh", group: "Skills", availability: "always", description: "Browse trending or all-time skills from skills.sh.", inputs: ["view", "page", "perPage"] },
  { name: "skills_curated", title: "Curated skills.sh", group: "Skills", availability: "always", description: "Browse skills.sh's official curated skill collection." },
  { name: "skills_get", title: "Fetch skill from skills.sh", group: "Skills", availability: "always", description: "Fetch a complete skill snapshot whose instructions can guide the connected AI for the current task.", inputs: ["id"] },
  { name: "skills_search", title: "Search skills.sh", group: "Skills", availability: "always", description: "Search the live skills.sh catalog for AI Agent Skills.", inputs: ["query", "limit"] },
  { name: "skills_use", title: "Use a skills.sh Skill", group: "Skills", availability: "always", description: "Find and fetch a skill so the connected AI can apply it to the current task. DEMO does not install or execute arbitrary skill code.", inputs: ["skill", "task", "level"] },
  { name: "text_diff", title: "Text / Document Diff", group: "Utilities", availability: "always", description: "Compare two texts or documents locally: mode=lines (structured added/removed/changed sections), mode=unified (unified-diff text), mode=json (deep JSON diff with exact paths). Optional normalization (web-noise/whitespace) for content with timestamps and counters. Markdown and other documents compare as text — added/removed lines, changed sections and a similarity score, structured for both humans and coding agents. Nothing is uploaded to any service.", inputs: ["mode", "a", "b", "normalize", "label_a", "label_b", "context_lines", "max_lines"] },
  { name: "url_inspect", title: "URL Safety Inspector", group: "Network", availability: "always", description: "Inspect a URL with DEMO's SSRF/security stack and report the verdict: parsing (scheme/host/port/path/query), scheme validation, hostname resolution with public/private classification, suspicious-pattern flags (open-redirect parameters, alternate IP notations, encoded control characters, userinfo tricks, downgrade/multi-host redirects) and — with follow_redirects — the full redirect chain with every hop re-validated plus the final destination and security-related response headers. Explicitly blocks localhost, RFC1918/loopback/link-local, metadata services, internal DNS zones and unsafe schemes — the same rules that protect every other tool (this never weakens them).", inputs: ["url", "follow_redirects", "max_redirects", "static_only"] },
  { name: "video_analyze", title: "Analyze Public Video (Unified)", group: "Video", availability: "vision", description: "The unified high-level video analysis tool: resolve the URL → retrieve the actual media → extract representative decoded frames (beginning, middle, end) → optionally extract and transcribe audio → return one structured evidence result. The payload contains access_status, source_url, canonical_url, duration, metadata (creator, post caption, dimensions, published stats), frames with timestamps delivered as MCP image content blocks, the transcript when one exists, limitations, and analysis_context telling you exactly what can and cannot be answered from this evidence. Text sources are kept strictly separate: textSources.transcript is real speech-to-text, textSources.platformCaption is the creator's post caption, textSources.generatedCaption is always unavailable (DEMO generates none), and textSources.onScreenText only exists when a vision model read the actual frames. If no frames and no transcript could be obtained, the result says so and MUST NOT be used to describe the video.", inputs: ["url", "question", "analysis_mode", "max_frames", "include_audio", "include_transcript", "frame_references"] },
  { name: "video_download_public", title: "Download Public Video", group: "Video", availability: "always", description: "Download a bounded, publicly accessible video into expiring Cloudflare R2 storage. It validates every redirect, content type, byte limit, timeout and known duration. It never sends cookies or bypasses login, CAPTCHA, DRM or private-account controls.", inputs: ["url", "max_size_mb"] },
  { name: "video_extract_audio", title: "Extract Public Video Audio", group: "Video", availability: "artifacts", description: "Best-effort extraction of a decoded public audio track using the browser Media Capture API. Returns an expiring audio artifact, or an honest no-audio/unsupported result; it never touches DRM or protected streams.", inputs: ["url", "video_reference", "max_seconds"] },
  { name: "video_extract_frames", title: "Extract Public Video Frames", group: "Video", availability: "frames", description: "Decode a public non-DRM video in Cloudflare Browser Rendering and return ACTUAL timestamped image content blocks plus expiring R2 references. Frames are rendered pixels seeked from the real <video> element — never thumbnails, posters, cover images or webpage screenshots. Representative sampling always covers the beginning, middle and end; explicit `timestamps` give targeted inspection. A URL or video_reference is required. When no frame can be decoded the result says so explicitly (success=false, FRAMES_UNAVAILABLE, frames=[]) instead of substituting metadata.", inputs: ["url", "video_reference", "timestamps", "interval_seconds", "frame_interval", "max_frames", "max_frame_count", "resize", "inline"] },
  { name: "video_fetch", title: "Fetch Actual Video Bytes", group: "Video", availability: "artifacts", description: "Retrieve the ACTUAL video file (not metadata, not a thumbnail) from a public URL or a previous video_reference, and store it as an expiring Cloudflare R2 artifact. The body is STREAMED into R2 through a bounded transform — a Worker never buffers the whole file and never touches a local disk. The first 128 KiB are inspected and must prove a real video container signature (ISO-BMFF/mp4/mov, Matroska/WebM, Ogg, MPEG-TS, FLV). If the response turns out to be an HTML page, a JSON error, a JPEG/PNG thumbnail, an audio-only file or an HLS/DASH manifest, the partial object is deleted and the call fails with NOT_A_VIDEO or UNSUPPORTED_MEDIA plus detected_as — a failed retrieval is never reported as a download. Enforces size, duration, timeout and content-type policy, validates every redirect hop against the SSRF guard, and never sends cookies or bypasses login, CAPTCHA, DRM or private-account controls.", inputs: ["url", "video_reference", "max_duration", "max_size_mb", "quality"] },
  { name: "video_get_frame", title: "Get Public Video Frame", group: "Video", availability: "artifacts", description: "Return one actual timestamped MCP image from a decoded public video or expiring video reference. It never returns a thumbnail in place of the requested video frame.", inputs: ["url", "video_reference", "timestamp", "inline"] },
  { name: "video_ingest", title: "Ingest Public Video", group: "Video", availability: "artifacts", description: "One-call public video ingestion. Validates the URL, follows only safe public redirects (TikTok https://www.tiktok.com/..., https://vm.tiktok.com/... and https://vt.tiktok.com/... short links supported), downloads the actual media file to expiring R2 storage, decodes real frames in Cloudflare Browser Run, and returns MCP image content blocks plus short-lived artifact URLs. Never bypasses CAPTCHAs, logins, paywalls or DRM; failures name the exact stage and stable error code.", inputs: ["url", "max_duration_seconds", "frame_count", "frame_interval_seconds", "include_audio", "include_transcript", "output_mode"] },
  { name: "video_inspect_pipeline", title: "Inspect Video Pipeline", group: "Video", availability: "always", description: "Diagnostic for the public video pipeline. Runs each stage in order — URL validation, redirect resolution, media discovery, browser access, actual media retrieval (64 KiB ranged sample), frame extraction, R2 upload (round trip), artifact URL generation and MCP response serialization — and reports exactly where it succeeds or fails. Never returns credentials, cookies or page bodies.", inputs: ["url", "include_download", "include_frames"] },
  { name: "video_inspect_url", title: "Inspect Public Video URL", group: "Video", availability: "always", description: "Resolve a public webpage or direct media URL, follow only safe public redirects, locate literal public video media, and return timestamped MCP image frames when Cloudflare Browser Run can decode them. Login walls, DRM and bot challenges are reported rather than bypassed.", inputs: ["url", "max_duration", "frame_interval", "include_transcript"] },
  { name: "video_react", title: "React to a Video (Grounded Evidence Package)", group: "Video", availability: "vision", description: "Prepare genuine, inspectable video evidence so YOU can react to what actually happens — DEMO does not write the reaction. It resolves the link, decodes real frames from throughout the video (returned as MCP image content blocks), attaches a transcript when one exists, and adds style-specific guidance plus frame-grounded observations when a server-side vision model is configured. `reaction` is always null and `reaction_author` is always \"connected_model\": there are no canned reactions and nothing is derived from the caption alone. Call this when the user says \"react to this\", \"what do you think\", \"look at this\", or sends a bare video link. Examine the returned frames first, then react in the requested style, anchoring claims to timestamps you can actually see. If visualEvidenceDelivered=false the retrieval failed: say so honestly and never pretend to have watched the video.", inputs: ["url", "style", "question", "max_frames", "include_audio"] },
  { name: "video_resolve", title: "Resolve Video URL", group: "Video", availability: "always", description: "Resolve a public video URL into its real identity and playable streams WITHOUT downloading or claiming to have watched anything. Follows TikTok short links (vt.tiktok.com, vm.tiktok.com) and canonical @user/video/<id> URLs as normal public redirects, validates every hop against the SSRF guard, and parses the page robustly from several independent sources (TikTok's __UNIVERSAL_DATA_FOR_REHYDRATION__ hydration payload with its published item status code, SIGI_STATE, schema.org JSON-LD, OpenGraph/Twitter meta and literal <video> elements) instead of one fragile selector. Returns canonical_url, video_id, creator, caption (which is NOT a transcript), duration, dimensions, every literal stream URL the page published with per-stream probe results, and — most importantly — access_status: public | deleted | private | login_required | region_restricted | challenge_required | rate_limited | not_found | expired | blocked_url | unsupported | unavailable | unknown. Use it to find out whether a video is actually retrievable before promising the user anything. CAPTCHAs, login walls, DRM and private accounts are reported, never bypassed. Signed CDN URLs are short-lived and are never logged or persisted.", inputs: ["url", "platform", "quality", "probe_limit", "verify_bytes", "include_signed_urls"] },
  { name: "video_transcribe", title: "Transcribe Public Video", group: "Video", availability: "transcription", description: "Produce timestamped speech-to-text for an expiring audio/video reference or public URL, using a configurable provider (Workers AI Whisper by default, or an explicitly configured HTTPS TRANSCRIPTION_ENDPOINT). Omit `language` for provider-side language detection, or pass a hint. Empty speech returns no_speech_detected; a missing provider returns TRANSCRIPTION_UNAVAILABLE. The result always states kind=speech_to_text and is_transcript=true so real transcribed speech can never be confused with a creator's post caption or with generated text — DEMO invents dialogue in no circumstance.", inputs: ["url", "video_reference", "audio_reference", "language"] },
  { name: "wayback", title: "Wayback Machine", group: "Internet Archive", availability: "always", description: "Wayback Machine operations on a public URL. mode=availability finds the closest snapshot to a timestamp (or now); mode=snapshots lists captures around a date/window; mode=retrieve fetches an archived page and extracts its content (title, text, links) with the capture timestamp preserved. If a URL was never archived, the result says snapshot: null with a clear message — DEMO never pretends every URL has an archived copy.", inputs: ["mode", "url", "timestamp", "from", "to", "limit", "match_type", "extract"] },
  { name: "web_diff", title: "Web Content Diff", group: "Web Intelligence", availability: "always", description: "Compare a webpage's content against a baseline: previous_text (supplied snapshot text), snapshot_key (a snapshot stored by web_extract/web_diff/web_monitor), or none (store the current page as a fresh baseline). Detects added, removed and changed content after normalizing obvious dynamic noise (timestamps, counters, tokens), and returns a structured diff + unified diff. Optionally stores the current page as a new snapshot. Screenshot-level visual comparison is screenshot_diff. Storage reuses DEMO's existing R2 artifact bucket with TTL cleanup — no new storage system.", inputs: ["url", "previous_text", "snapshot_key", "normalize", "store_snapshot", "include_unified_diff", "timeout_ms"] },
  { name: "web_extract", title: "Extract Webpage Content", group: "Web Intelligence", availability: "always", description: "Fetch a public webpage and extract clean content: title, description, author, publication date, headings, paragraphs, links, images, tables, metadata and JSON-LD structured data. format=text (clean text), format=markdown (headings/lists/tables/links preserved), format=metadata (structured JSON). Runs on fetched HTML through DEMO's shared extractor — for JS-rendered pages use the existing browser_* tools instead. Nothing is stored or tracked; SSRF, size and timeout limits apply.", inputs: ["url", "format", "include_links", "max_chars", "store_snapshot", "timeout_ms"] },
  { name: "web_monitor", title: "Website Change Monitor", group: "Web Intelligence", availability: "snapshots", description: "Register a URL for content-change monitoring on DEMO's existing R2 bucket (expiring objects; TTL cleanup like every artifact). mode=add (register + store baseline snapshot), mode=check (fetch now and report added/removed/changed content with a change summary), mode=list, mode=remove, mode=history (recent check versions). Checks run only when you ask (or via the opt-in scheduled sweep WEB_MONITOR_SCHEDULED_CHECKS=true) — registering never silently creates an unbounded recurring job. Every check respects SSRF protection, timeouts, size limits and rate limits. Retention is configurable per monitor.", inputs: ["mode", "url", "monitor_id", "interval_seconds", "max_versions", "retention_seconds", "normalize", "force"] },
  { name: "web_research", title: "Structured Web Research", group: "Research", availability: "always", description: "Run structured research on a question: discover relevant public sources, retrieve them (live, or via the Wayback Machine when the live page is gone), extract useful content, compare multiple sources, and return evidence-backed findings with FULL provenance (every statement carries source URLs + retrieval timestamps). Findings separate quoted facts from labelled inference, conflicts between sources are reported as conflicts (never resolved by guessing) and confidence reflects corroboration depth — never a claim of truth. Configurable depth (quick/standard/deep), maximum sources, timeout and domain allow/deny lists. Sources needing CAPTCHA, login or other human interaction are reported with the existing human-handoff hint (browser_captcha_handoff / browser_pause_for_human) — protections are never bypassed. Never fabricate citations: answer from findings and cite their sources.", inputs: ["question", "depth", "max_sources", "timeout_ms", "allowed_domains", "blocked_domains", "include_archive_fallback"] },
  { name: "youtube_channel", title: "Get YouTube Channel Info", group: "YouTube", availability: "youtube", description: "Retrieve public metadata for a YouTube channel by channel ID, @handle, or channel URL. Returns title, description, statistics, thumbnails. Requires YOUTUBE_API_KEY secret.", inputs: ["url_or_id"] },
  { name: "youtube_playlist", title: "Get YouTube Playlist Info", group: "YouTube", availability: "youtube", description: "Retrieve public metadata for a YouTube playlist by playlist ID or URL. Optionally includes playlist items. Requires YOUTUBE_API_KEY secret.", inputs: ["url_or_id", "include_items", "max_items"] },
  { name: "youtube_search", title: "Search Public YouTube", group: "YouTube", availability: "youtube", description: "Search public YouTube videos, channels, or playlists using the YouTube Data API v3. Returns public metadata (titles, descriptions, thumbnails, channel names). Does not retrieve actual video content — use inspect_video for that. Requires YOUTUBE_API_KEY secret.", inputs: ["query", "type", "max_results", "page_token"] },
  { name: "youtube_video", title: "Get YouTube Video Info", group: "YouTube", availability: "youtube", description: "Retrieve public metadata for a YouTube video by URL or video ID. Returns title, description, channel, duration, thumbnails, statistics, and access status. Also reports whether the existing video pipeline (inspect_video) can retrieve actual frames/audio from this video. Requires YOUTUBE_API_KEY secret. Supported URL forms: youtube.com/watch?v=…, youtu.be/…, youtube.com/shorts/…, youtube.com/embed/…", inputs: ["url_or_id"] },
];

export const TOOL_GROUPS: string[] = ["Internet Archive","Browser","Utilities","Core","Feeds","Git","Documents","Video","JEV","Laya","Network","Roblox","Skills","Web Intelligence","Research","YouTube"];

export const TOOL_CATALOG_COUNT = TOOL_CATALOG.length;
